import React from 'react';

const features = [
  {
    icon: '🤖',
    title: 'AI-Powered Workouts',
    description: 'Get personalized workout plans generated by advanced AI algorithms based on your fitness level and goals.',
  },
  {
    icon: '🥗',
    title: 'Smart Nutrition Tracking',
    description: 'Track your meals with intelligent food recognition and get personalized nutrition recommendations.',
  },
  {
    icon: '📊',
    title: 'Progress Analytics',
    description: 'Monitor your progress with detailed analytics and insights to help you stay motivated and on track.',
  },
  {
    icon: '🏆',
    title: 'Achievement System',
    description: 'Unlock achievements and milestones as you progress towards your fitness goals.',
  },
  {
    icon: '📱',
    title: 'Mobile & Web Access',
    description: 'Access your fitness coach anywhere with our mobile app and web platform.',
  },
  {
    icon: '🔔',
    title: 'Smart Reminders',
    description: 'Get intelligent reminders for workouts, meals, and hydration based on your schedule.',
  },
];

export const Features: React.FC = () => {
  return (
    <section className="py-16 bg-gray-50">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Powerful Features for Your Fitness Journey
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Everything you need to achieve your fitness goals, powered by artificial intelligence
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <div
              key={index}
              className="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow duration-300"
            >
              <div className="text-4xl mb-4">{feature.icon}</div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">
                {feature.title}
              </h3>
              <p className="text-gray-600 leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
        
        <div className="text-center mt-12">
          <button className="bg-indigo-600 text-white px-8 py-3 rounded-lg font-semibold hover:bg-indigo-700 transition-colors duration-200">
            Start Your Journey Today
          </button>
        </div>
      </div>
    </section>
  );
};
