name: Deploy Landing Page to GitHub Pages

on:
  push:
    branches: ["main", "master"]
    paths: ["apps/landing-page/**"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-landing"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          npm ci

      - name: Build shared packages first
        run: |
          cd packages/utils
          npm run build
          cd ../shared-types
          npm run build
          cd ../api-client
          npm run build
          cd ../ui-components
          npm run build

      - name: Install landing page dependencies
        run: |
          cd apps/landing-page
          npm ci

      - name: Build Landing Page
        run: |
          cd apps/landing-page
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/landing-page/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
